/* Auto-generated by cbindgen from crates/tunnelcat-proto. Do not edit. */
#ifndef TUNNELCAT_PROTO_H
#define TUNNELCAT_PROTO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/// A version string identifying this build of the protocol crate.
/// Returned as a `const char *` pointing to a static, NUL-terminated
/// UTF-8 string. The caller (Go) must NOT free this pointer.
const char *tunnelcat_proto_version(void);

/// Test that a C string round-trips through Rust correctly.
/// The returned pointer is a freshly allocated C string that the
/// caller MUST free (via C.free / std::free).
const char *tunnelcat_proto_echo(const char *input);

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* TUNNELCAT_PROTO_H */
